language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - nightly
  - hhvm

matrix:
  include:
    - php: 5.3
      env: deps=low
    - nightly
    - hhvm
    - hhvm-nightly
  allow_failures:
      - php: nightly
  fast_finish: true

env:
  global:
    - deps=no

before_install:
  - travis_retry composer self-update

install:
  - if [ "$deps" = "no" ]; then composer --prefer-source install; fi;
  - if [ "$deps" = "low" ]; then composer --prefer-source --prefer-lowest --prefer-stable update; fi;
